/**
 * @file
 * @brief Chinese scroll appearance descriptors for unidentified scroll naming.
 *
 * When the game language is Chinese, unidentified scrolls use a physical
 * appearance description system (binding material + seal type) instead of
 * the Latin-alphabet labels generated by make_name(MNAME_SCROLL).
 *
 * The binding/seal indices are derived deterministically from the existing
 * subtype_rnd field, so no save format changes are needed.
 */

#pragma once

enum scroll_binding_type
{
    SBI_RED_SILK,       // 红绸带
    SBI_BLUE_SILK,      // 蓝绸带
    SBI_HEMP_CORD,      // 麻绳
    SBI_GOLD_THREAD,    // 金丝线
    SBI_SILVER_THREAD,  // 银丝线
    SBI_LEATHER_CORD,   // 皮绳
    SBI_GREEN_SILK,     // 绿绸带
    SBI_PURPLE_SILK,    // 紫绸带
    SBI_BLACK_THREAD,   // 黑丝线
    SBI_WHITE_SILK,     // 白绸带
    SBI_COPPER_CHAIN,   // 铜链
    SBI_PLAIN_BAND,     // 素色带
    NDSC_SCROLL_BINDING
};

enum scroll_seal_type
{
    SSE_WAX,            // 蜡封
    SSE_GOLD_FOIL,      // 金箔封
    SSE_SILVER_FOIL,    // 银箔封
    SSE_BONE_CLASP,     // 骨扣
    SSE_JADE_CLASP,     // 玉扣
    SSE_COPPER_CLASP,   // 铜扣
    SSE_TIN,            // 锡封
    SSE_SEALING_WAX,    // 火漆印
    SSE_TALISMAN,       // 符纸封
    SSE_NONE,           // (无封印)
    NDSC_SCROLL_SEAL
};

extern const char* const scroll_binding_zh[];
extern const char* const scroll_seal_zh[];
