#!/usr/bin/env python3

"""
Works with both Python 2 & 3. If that changes, update how the Makefile calls
this.
"""

from subprocess import Popen, PIPE

import os
import shlex
import sys

if len(sys.argv) < 2:
    sys.stderr.write('CXX not specified\n')
    sys.exit(1)

# Not just the name of the compiler, it can have arguments too. Preserve the
# flags passed separately by the Makefile as well.
CXX = sys.argv[1]
command = shlex.split(CXX) + sys.argv[2:] + ['-c', 'conftest.cc']


def cleanup_probe_files():
    for filename in ('conftest.cc', 'conftest.o', 'conftest.obj'):
        try:
            os.remove(filename)
        except OSError:
            pass


def compile_probe(source):
    out = open('conftest.cc', 'w')
    out.write(source)
    out.close()

    try:
        process = Popen(command, stdout=PIPE, stderr=PIPE)
    except OSError as error:
        cleanup_probe_files()
        sys.stderr.write('Could not run C++ compiler; config.h was not updated\n')
        sys.stderr.write(str(error) + '\n')
        sys.exit(1)
    (output, err) = process.communicate()
    return process.returncode, output, err


def feature_probe(source, macro):
    exit_code, _, _ = compile_probe(source)
    return ("#define " if exit_code == 0 else "#undef ") + macro


# Distinguish a missing platform feature from a compiler/wrapper failure. A
# failed sanity probe must not replace a valid config.h with all-undef output.
exit_code, _, sanity_err = compile_probe("""
int main()
{
    return 0;
}
""")
if exit_code != 0:
    cleanup_probe_files()
    sys.stderr.write('C++ compiler sanity check failed; config.h was not updated\n')
    if not isinstance(sanity_err, str):
        sanity_err = sanity_err.decode('utf-8', 'replace')
    sys.stderr.write(sanity_err)
    sys.exit(exit_code or 1)

FDATASYNC = feature_probe("""
#include <unistd.h>
int main()
{
    fdatasync(1);
    return 0;
}
""", "CRAWL_HAVE_FDATASYNC")

STRLCPY = feature_probe("""
#include <cstring>
using namespace std;
int main()
{
    const char *src = "hello";
    char dst[10];
    strlcpy(dst, src, sizeof(dst));
    return 0;
}
""", "CRAWL_HAVE_STRLCPY")

MKSTEMP = feature_probe("""
#include <cstdlib>
using namespace std;
int main()
{
    char file[] = "XXXXXX";
    mkstemp(file);
    return 0;
}
""", "CRAWL_HAVE_MKSTEMP")

USLEEP = feature_probe("""
#include <unistd.h>
int main()
{
    usleep(0);
    return 0;
}
""", "CRAWL_HAVE_USLEEP")

cleanup_probe_files()

output_contents = """#pragma once

// Generated by util/configure.py

"""
output_contents += FDATASYNC
output_contents += '\n'
output_contents += STRLCPY
output_contents += '\n'
output_contents += MKSTEMP
output_contents += '\n'
output_contents += USLEEP
output_contents += '\n'

contents_match = False
try:
    config_file = open('config.h', 'r')
    current_contents = config_file.read()
    config_file.close()
    contents_match = current_contents == output_contents
except OSError:
    pass

if not contents_match:
    out = open('config.h', 'w')
    out.write(output_contents)
    out.close()
