#!/bin/sh
# Run this as crawl-ref/source/util/edit_vault from the repository root, or add
# crawl-ref/source/util/ to PATH before defining a short shell alias.
#
# You need to define $EDITOR as well; on Debian there's some weak-ass
# autodetection but that's unlikely to match _your_ preferences. And it
# may start something as vile as vi.

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
SOURCE_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
cd "$SOURCE_DIR" || exit 1

if [ -z "$1" ]
  then
    echo >&2 "Usage: edit-vault vault_name"
    exit 1
fi

V=`grep -rHn --include='*.des' "NAME: *$1$" dat`
if [ -z "$V" ]
  then
    echo >&2 "Vault \"$1\" not found."
    exit 1
fi

if which sensible-editor >/dev/null
  then
    ED=sensible-editor
  else
    ED="${EDITOR:-editor}"
fi

FILE="${V%%:*}"
LINE="${V#*:}"; LINE="${LINE%%:*}"

"$ED" +"$LINE" "$FILE"
